### ISSUE TITLE
不支持double类型

### ISSUE THREAD

**Issue by walking-with-linght** [zhangshiqian1214/sprotojs#15]
let serverHost = server.host();
                        ^

TypeError: Cannot read property 'host' of null
    at Object.<anonymous> (D:\工作\sproto-js\test\test.js:16:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

sproto.js 未改动

**Comment by zhangshiqian1214** [comment]
你把sproto定义double的协议和test.js用的代码贴一下，我看看什么问题

**Comment by walking-with-linght** [comment]
sproto中：
```
.UserInfo {
	id 				0  : string
       gold 			2 : integer	# 金币 之前的double
      nickname 		38 : string
	test_double		1 : double		# 测试
}
```
（已正确使用该结构体）
test.js中：
```

let sproto = require(".././sproto");
let fs = require("fs");

function readBinary(filename) {
    let buffer = fs.readFileSync(filename);
    if (!buffer) {
        console.log("not found file(" + filename + ")");
    }
    return buffer;
}

let server = sproto.createNew(readBinary("c2s_all.spb"));
// server.dump();

let serverHost = server.host();
let serverSender = serverHost.attach(sproto.createNew(readBinary("s2c_all.spb")));

let client = sproto.createNew(readBinary("s2c_all.spb"));
// client.dump();

let clientHost = client.host();
let clientSender = clientHost.attach(sproto.createNew(readBinary("c2s_all.spb")));

// 客户端请求应答流程
{

    // 1. 客户端传输数据给服务器
    let buffer = clientSender("GetUserInfo",null, 1);

    // console.log(buffer);
    // 2. 服务端接收处理数据, 再返回数据给客户端
    let ret = serverHost.dispatch(buffer);
    console.log(ret);
    console.log("==========================");
    buffer = ret.responseFunc({  userInfo: { nickname: "先知比利", id: 0, gold: 4294967 } });

    // 3. 客户端接收服务器的返回数据
    ret = clientHost.dispatch(buffer);
    console.log(ret);
}
```

spb文件已确认可用，
test_double字段存在时报错如下：
```
D:\工作\sproto-js\test>node test.js
D:\工作\sproto-js\test\test.js:16
let serverHost = server.host();
                        ^

TypeError: Cannot read property 'host' of null
    at Object.<anonymous> (D:\工作\sproto-js\test\test.js:16:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
请按任意键继续. . .
```

去掉test_double字段时打印如下：
```
D:\工作\sproto-js\test>node test.js
{ type: 'REQUEST',
  pname: 'GetUserInfo',
  result: undefined,
  responseFunc: [Function],
  session: 1 }
==========================
{ type: 'RESPONSE',
  session: 1,
  result:
   { userInfo: { id: '', gold: 4294967, nickname: '先知比利' } } }
请按任意键继续. . .
```

**Comment by zhangshiqian1214** [comment]
使用你提供的信息模拟测试了一下，double确实有问题，已经提交了，下面的测试我这边通过了，你再看看还有没有问题

协议文件：
```
.Package {
	type    0  : integer
	session 1  : integer
	ud      2  : binary
}

.UserInfoReq {
	
}

.UserInfo {
	id 				0  : string
	test_double		1  : double		# 测试
    gold 			2  : integer	# 金币 之前的double
    nickname 		3 : string
}

GetUserInfo 101 {
	request UserInfoReq
	response {
		userInfo 0 : UserInfo
	}
}

```


测试代码：
```lua
var fs = require("fs");
var sproto = require("./sproto");
var utils = require("./utils");

var filename = "./c2s_all.spb";
var buffer = fs.readFileSync(filename);
if (buffer == null){
	console.log("read File err1");
}
console.log(sproto);

let server = sproto.createNew(buffer);
let serverHost = server.host("Package");
let serverSender = serverHost.attach(server);

let client = sproto.createNew(buffer);
let clientHost = client.host("Package");
let clientSender = clientHost.attach(client);

var sp = sproto.createNew(buffer);
console.log(sp);


// 客户端请求应答流程
{

    // 1. 客户端传输数据给服务器
    let buffer = clientSender("GetUserInfo",null, 1);

    // console.log(buffer);
    // 2. 服务端接收处理数据, 再返回数据给客户端
    let ret = serverHost.dispatch(buffer);
    console.log(ret);
    console.log("==========================");
    buffer = ret.responseFunc({userInfo : { nickname: "先知比利", id: "123", gold: 4294967, test_double : 1999999999.321 }});

    // 3. 客户端接收服务器的返回数据
    ret = clientHost.dispatch(buffer);
    console.log(ret);
}
```

**Comment by walking-with-linght** [comment]
测试可用
另外请教一下，integer支持多少位数字？在你修复前我发现integer任然支持大于2^32次方数字。。所以之前没有及时回复你。现在double最高支持多少位数字呢，我们项目需要用到大数据...

**Comment by zhangshiqian1214** [comment]
double是8字节64位的，integer支持8字节52位，原因是js的数字类型特性

**Comment by zhangshiqian1214** [comment]
具体位数你看IEEE754标准

**Comment by walking-with-linght** [comment]
很抱歉重新打开了这个issue，上面的测试是用js收发模拟当客户端解析的sproto，但用到项目中出错了，服务端用的skynet，字段改为了double，客户端更新本项目后发现收到的double数据异常，比如
```
客户端收到的金币字段为，实际为900000
gold: 5.3435753e-315
```
前端用的layabox，typescript
如果没有测试环境，可以留下联系方式么

**Comment by zhangshiqian1214** [comment]
加我qq814729280

**Comment by zhangshiqian1214** [comment]
我也有用skynet做服务端，js客户端解析，你可以用下面的函数在skynet把发送的数据打印成二进制流，然后贴上来，加上客户端协议sproto,也能测试
```lua
---@param byteStream string
---@return string,table
function string.toByteArray(byteStream)
    local byteArray = {}
    local ret = string.gsub(byteStream, "(.)", function(c)
        table.insert(byteArray, string.byte(c))
    end)
    return string.format("[%s]", table.concat(byteArray, ",")), byteArray
end

print("buffer=", string.toByteArray(buffer))
```

```
--输出类似这样的
buffer=[13,14,15,156]
```

**Comment by walking-with-linght** [comment]
大哥牛批，已解决
